### ISSUE TITLE
calculate-seaice-extent

### ISSUE THREAD

**Issue by ronygolderku** [coastwatch-training/CoastWatch-Tutorials#46]
Hi there,
I am Rony. Thanks for making this awesome repository.
While exploring the contents of the repository [[working-with-sea-ice-conc-data/working-with-sea-ice-conc-data.ipynb](https://github.com/coastwatch-training/CoastWatch-Tutorials/blob/main/calculate-seaice-extent/Python/calculating-sea-ice-extent.ipynb)], I noticed that the dataset dimensions `ygrid `and` xgrid `are represented in metres/kilometers.

I am particularly interested in learning how to crop/slice the sea ice dataset based on latitude and longitude coordinates. Given that the dataset utilizes `ygrid `and `xgrid` dimensions, I would like to understand the process of clipping (cropping) the dataset using latitude and longitude coordinates. Alternatively, if possible, I would also like to explore the option of using a shapefile for cropping purposes.

Thank you for your time and assistance.

Rony

**Comment by shospital** [comment]
@ronygolderku 

Hello Rony, I have uploaded few utility functions to process the sea ice data.  here you can crop using a shapefile with geometries from different projection than that of the sea ice data.  please take a look at it and see if you can manipulate the python code for your needs. 

https://github.com/polarwatch/data-proc-utilities/blob/main/python/clip_data_to_shapefile.ipynb
