### ISSUE TITLE
review ATN notebooks

### ISSUE THREAD

**Issue by shospital** [coastwatch-training/CoastWatch-Tutorials#52]
@DaisyShi19 PR was approved and merged. there were few conflicts which I believe I manually fixed. could you review all your updated files and check if they are up to date?

**Comment by DaisyShi19** [comment]
Thanks Sunny. All files are up to date as of this pull request.

One thing I noticed is that I only modified and pushed changes in the "matchup-satellite-data-to-track-locations" folder, is it normal that the pull request "[Minor edits (#51)" shows in the "last commit message" for other folders?

**Comment by shospital** [comment]
@DaisyShi19 are the commit messages from you or someone else? 

I am not sure if I understood your question correctly.

**question: other commits are included in the PR:**
You can create a PR for a dev branch branch and you can continue to push new commits to the dev branch as long as merge hasn't occured yet. Let's say you pushed dev and made PR, but you made more edits and pushed to the dev branch, all commits will be undeer the same PR.

**question: other commits that I have not made are included in the PR**
There were some conflicts between main and your branch. In order to fix it, I had to merge the main into your branch locally, resolve conflicts, and push your branch to the remote.  all these were included in the PR. 

I hope one of the two scenarios answered your question. pls let me know if you have other questions!

**Comment by DaisyShi19** [comment]
Hi Sunny, I did make two the commits within one pull request. But I didn't commit all changes in my branch to this pull request. Only the ones related to satellite ATN matchup are committed to the pull request. 

Other changes in my local branch should not be pushed/merged to main. Is this what's been done here?

**Comment by shospital** [comment]
I am not sure exactly what happened but your branch and the main had conflicts.
Best practices should be 
1. merge to main as soon as it's ready (Sunny should have merged sooner) 
2. always create a new branch from freshly pulled main before making changes.
